// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sucursal360.Web.Data;

#nullable disable

namespace Sucursal360.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260812201005_AddSucursal360Domain")]
    partial class AddSucursal360Domain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b6f7be6-4d47-4b68-a3fa-7a104369b36a",
                            ConcurrencyStamp = "7b6f7be6-4d47-4b68-a3fa-7a104369b36a",
                            Name = "Administrador",
                            NormalizedName = "ADMINISTRADOR"
                        },
                        new
                        {
                            Id = "443f48d3-df72-45b9-84a1-1d28dc9f6bb4",
                            ConcurrencyStamp = "443f48d3-df72-45b9-84a1-1d28dc9f6bb4",
                            Name = "GerenteCorporativo",
                            NormalizedName = "GERENTECORPORATIVO"
                        },
                        new
                        {
                            Id = "531e9b7f-d5b9-4695-bad0-034525ef5f64",
                            ConcurrencyStamp = "531e9b7f-d5b9-4695-bad0-034525ef5f64",
                            Name = "GerenteSucursal",
                            NormalizedName = "GERENTESUCURSAL"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sucursal360.Web.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AssignedBranchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedBranchId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalPlaceId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Provider", "ExternalPlaceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Branches_Provider_ExternalPlaceId")
                        .HasFilter("ExternalPlaceId IS NOT NULL");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-4111-8111-111111111111"),
                            Code = "SUC-001",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalPlaceId = "DEMO-SUC-001",
                            IsActive = true,
                            Name = "Cafe Horizonte Centro",
                            Provider = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-4222-8222-222222222222"),
                            Code = "SUC-002",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalPlaceId = "DEMO-SUC-002",
                            IsActive = true,
                            Name = "Cafe Horizonte Carretera Sur",
                            Provider = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-4333-8333-333333333333"),
                            Code = "SUC-003",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalPlaceId = "DEMO-SUC-003",
                            IsActive = true,
                            Name = "Cafe Horizonte Galerias",
                            Provider = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-8444-444444444444"),
                            Code = "SUC-004",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalPlaceId = "DEMO-SUC-004",
                            IsActive = true,
                            Name = "Cafe Horizonte Metrocentro",
                            Provider = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-4555-8555-555555555555"),
                            Code = "SUC-005",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ExternalPlaceId = "DEMO-SUC-005",
                            IsActive = true,
                            Name = "Cafe Horizonte Las Colinas",
                            Provider = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.BranchSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BusinessStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IntegrationRunId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningHoursJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(2, 1)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationRunId");

                    b.HasIndex("BranchId", "RetrievedAtUtc")
                        .HasDatabaseName("IX_BranchSnapshots_Branch_Date");

                    b.HasIndex("BranchId", "Provider", "RetrievedAtUtc")
                        .IsUnique()
                        .HasDatabaseName("UX_BranchSnapshots_Branch_Provider_Date");

                    b.ToTable("BranchSnapshots", t =>
                        {
                            t.HasCheckConstraint("CK_BranchSnapshots_Latitude", "Latitude IS NULL OR Latitude BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_BranchSnapshots_Longitude", "Longitude IS NULL OR Longitude BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_BranchSnapshots_Rating", "Rating IS NULL OR Rating BETWEEN 1.0 AND 5.0");

                            t.HasCheckConstraint("CK_BranchSnapshots_ReviewCount", "ReviewCount IS NULL OR ReviewCount >= 0");
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.IntegrationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordsReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("RecordsStored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicalMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .IsUnique();

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("BranchId", "StartedAtUtc")
                        .HasDatabaseName("IX_IntegrationRuns_Branch_Date");

                    b.HasIndex("Status", "StartedAtUtc")
                        .HasDatabaseName("IX_IntegrationRuns_Status_Date");

                    b.ToTable("IntegrationRuns", t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationRuns_Counts", "RecordsReceived >= 0 AND RecordsStored >= 0");
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalReviewId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("RetrievedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "PublishedAtUtc")
                        .HasDatabaseName("IX_Reviews_Branch_Published");

                    b.HasIndex("BranchId", "Rating")
                        .HasDatabaseName("IX_Reviews_Branch_Rating");

                    b.HasIndex("Provider", "ExternalReviewId")
                        .IsUnique()
                        .HasDatabaseName("UX_Reviews_Provider_ExternalId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating", "Rating IS NULL OR Rating BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ReviewCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1"),
                            Code = "SERVICIO",
                            Description = "Atencion, cortesia, conocimiento o actitud del personal",
                            IsActive = true,
                            Name = "Servicio"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2"),
                            Code = "ESPERA",
                            Description = "Filas, demora en ordenar, preparacion o entrega",
                            IsActive = true,
                            Name = "Tiempo de espera"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3"),
                            Code = "CALIDAD",
                            Description = "Sabor, temperatura, presentacion o consistencia",
                            IsActive = true,
                            Name = "Calidad del producto"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4"),
                            Code = "LIMPIEZA",
                            Description = "Mesas, banos, utensilios o percepcion de higiene",
                            IsActive = true,
                            Name = "Limpieza"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5"),
                            Code = "PRECIO",
                            Description = "Valor percibido, promociones o relacion precio-calidad",
                            IsActive = true,
                            Name = "Precio"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa6"),
                            Code = "INSTALACIONES",
                            Description = "Ambiente, espacio, estacionamiento, comodidad o ruido",
                            IsActive = true,
                            Name = "Instalaciones"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa7"),
                            Code = "OTROS",
                            Description = "Tema relevante que no corresponde a las categorias anteriores",
                            IsActive = true,
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategoryAssignment", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReviewCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("ReviewId", "ReviewCategoryId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("ReviewCategoryId")
                        .HasDatabaseName("IX_ReviewCategoryAssignments_Category");

                    b.ToTable("ReviewCategoryAssignments");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategoryAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReviewCategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ReviewCategoryId");

                    b.HasIndex("ReviewId", "ChangedAtUtc")
                        .HasDatabaseName("IX_ReviewCategoryAudits_Review_Date");

                    b.ToTable("ReviewCategoryAudits");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.SimulatedDataImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ImportedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImportedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("RowCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByUserId");

                    b.ToTable("SimulatedDataImports", t =>
                        {
                            t.HasCheckConstraint("CK_Imports_Period", "PeriodEnd >= PeriodStart");
                        });
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.SimulatedOperationalMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NIO")
                        .IsFixedLength();

                    b.Property<int>("DataOrigin")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetSales")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportId")
                        .HasDatabaseName("IX_SimulatedMetrics_Import");

                    b.HasIndex("BranchId", "BusinessDate")
                        .IsUnique()
                        .HasDatabaseName("UX_SimulatedMetrics_Branch_Date");

                    b.ToTable("SimulatedOperationalMetrics", t =>
                        {
                            t.HasCheckConstraint("CK_SimulatedMetrics_NetSales", "NetSales >= 0");

                            t.HasCheckConstraint("CK_SimulatedMetrics_Origin", "DataOrigin = 1");

                            t.HasCheckConstraint("CK_SimulatedMetrics_Transactions", "TransactionCount >= 0");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sucursal360.Web.Data.ApplicationUser", b =>
                {
                    b.HasOne("Sucursal360.Web.Domain.Entities.Branch", "AssignedBranch")
                        .WithMany()
                        .HasForeignKey("AssignedBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedBranch");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.BranchSnapshot", b =>
                {
                    b.HasOne("Sucursal360.Web.Domain.Entities.Branch", "Branch")
                        .WithMany("Snapshots")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.IntegrationRun", "IntegrationRun")
                        .WithMany("Snapshots")
                        .HasForeignKey("IntegrationRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("IntegrationRun");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.IntegrationRun", b =>
                {
                    b.HasOne("Sucursal360.Web.Domain.Entities.Branch", "Branch")
                        .WithMany("IntegrationRuns")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("TriggeredByUser");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.Review", b =>
                {
                    b.HasOne("Sucursal360.Web.Domain.Entities.Branch", "Branch")
                        .WithMany("Reviews")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategoryAssignment", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.ReviewCategory", "ReviewCategory")
                        .WithMany("Assignments")
                        .HasForeignKey("ReviewCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.Review", "Review")
                        .WithMany("CategoryAssignments")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Review");

                    b.Navigation("ReviewCategory");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategoryAudit", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.ReviewCategory", "ReviewCategory")
                        .WithMany("Audits")
                        .HasForeignKey("ReviewCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.Review", "Review")
                        .WithMany("CategoryAudits")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Review");

                    b.Navigation("ReviewCategory");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.SimulatedDataImport", b =>
                {
                    b.HasOne("Sucursal360.Web.Data.ApplicationUser", "ImportedByUser")
                        .WithMany()
                        .HasForeignKey("ImportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.SimulatedOperationalMetric", b =>
                {
                    b.HasOne("Sucursal360.Web.Domain.Entities.Branch", "Branch")
                        .WithMany("SimulatedOperationalMetrics")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sucursal360.Web.Domain.Entities.SimulatedDataImport", "Import")
                        .WithMany("Metrics")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Import");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.Branch", b =>
                {
                    b.Navigation("IntegrationRuns");

                    b.Navigation("Reviews");

                    b.Navigation("SimulatedOperationalMetrics");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.IntegrationRun", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.Review", b =>
                {
                    b.Navigation("CategoryAssignments");

                    b.Navigation("CategoryAudits");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.ReviewCategory", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Audits");
                });

            modelBuilder.Entity("Sucursal360.Web.Domain.Entities.SimulatedDataImport", b =>
                {
                    b.Navigation("Metrics");
                });
#pragma warning restore 612, 618
        }
    }
}
