namespace Sucursal360.Web.ViewModels.Dashboard;

public sealed record CorporateDashboardBranchRowViewModel(
    Guid BranchId,
    string Code,
    string Name,
    bool IsActive,
    string Provider,
    string ExternalPlaceId,
    string BusinessStatus,
    string DataStatus,
    decimal? Rating,
    decimal? RatingDelta,
    int? ReviewCount,
    int? ReviewCountDelta,
    int PeriodReviewCount,
    int NegativeReviewCount,
    string TopNegativeCategory,
    decimal? NetSales,
    int? TransactionCount,
    decimal? AverageTicket,
    string Currency,
    string AttentionLevel,
    string AttentionReason,
    DateTimeOffset? RetrievedAtUtc,
    string SourceLabel);
