name: Deploy Azure App Service

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: 10.0.x
  PROJECT_PATH: src/Sucursal360.Web/Sucursal360.Web.csproj
  PUBLISH_DIR: publish

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Sucursal360.slnx -m:1 -nr:false

      - name: Build
        run: dotnet build Sucursal360.slnx -m:1 -nr:false --configuration Release --no-restore

      - name: Test
        run: dotnet test Sucursal360.slnx -m:1 -nr:false --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-restore --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.PUBLISH_DIR }}
